sql-lite-file: players.db

resources:
    OAK_LOG:
        type: "tree"
        drop:
            sapling: OAK_SAPLING
            sapling_name: "&cApple Sapling"
            leaf: OAK_LEAVES
            log: OAK_LOG
            item: APPLE:3
            durability: 3

recipes:
    basicaxe:
        name: "&3Basic Axe"
        permission: animalcrossing.items.basicaxe
        item: STONE_AXE
        cost: 500
        recipe:
            - 0:STONE
            - 1:STONE
            - 3:STONE
            - 4:STICK
            - 7:STICK
    basicshovel:
        name: "&3Basic Shovel"
        permission: animalcrossing.items.basicshovel
        item: STONE_SHOVEL
        cost: 500
        recipe:
            - 1:STONE
            - 4:STICK
            - 7:STICK
    basicrod:
        name: "&3Basic Rod"
        permission: animalcrossing.items.basicrod
        item: FISHING_ROD
        cost: 500
        recipe:
            - 2:STICK
            - 4:STICK
            - 5:STICK
            - 6:STICK
            - 8:STRING
    applesapling:
        name: "&cApple Sapling"
        permission: animalcrossing.items.applesapling
        item: OAK_SAPLING
        cost: 1000
        recipe:
            - 0:WHEAT_SEEDS
            - 1:WHEAT_SEEDS
            - 2:WHEAT_SEEDS
            - 3:WHEAT_SEEDS
            - 4:APPLE
            - 5:WHEAT_SEEDS
            - 6:WHEAT_SEEDS
            - 7:WHEAT_SEEDS
            - 8:WHEAT_SEEDS
    sturdyaxe:
        name: "&bSturdy Axe"
        permission: animalcrossing.items.sturdyaxe
        item: IRON_AXE
        cost: 5000
        recipe:
            - 0:IRON_INGOT
            - 1:IRON_INGOT
            - 3:IRON_INGOT
            - 4:IRON_BLOCK
            - 7:STICK

