main: me.specifies.AnimalCrossing.Main
version: 1.0
author: SpecifiesDev
name: AnimalCrossing
api-version: 1.16

commands:
    info:
        usage: /info
        description: Opens an inventory displaying a player's information.
    setbells:
        usage: /setbells [player] [bells]
        description: Allows a superadmin to change how many bells a player has.
    setmiles:
        usage: /setmiles [player] [miles]
        description: Allows a superadmin to change how many miles a player has.
    recipes:
        usage: /recipes
        description: Shows a player their unlocked recipes.